"use client";

import Link from "next/link";
import { Activity, ArrowLeft, Baby, CalendarDays, ChevronLeft, Clock3, Cross, HeartPulse, Images, Layers3, MapPin, ScanLine, ShieldCheck, SmilePlus, Sparkles, Stethoscope } from "lucide-react";
import type { ComponentType } from "react";
import type { Branch, Department } from "@/types";
import { services } from "@/data/services";
import { SafeImage } from "./safe-image";
import { Reveal, SectionTitle } from "./ui";

const icons: Record<string, ComponentType<{ size?: number }>> = { sparkles: Sparkles, shield: ShieldCheck, smile: SmilePlus, activity: Activity, baby: Baby, layers: Layers3, heart: HeartPulse, cross: Cross, scan: ScanLine };

export function BranchHero({ branch }: { branch: Branch }) {
  return <section className="branch-hero"><SafeImage src={branch.heroImage} fallbackSrc={branch.heroFallback} alt={`واجهة ${branch.name}`} fill priority sizes="100vw" fallbackLabel={`صورة ${branch.name}`} /><div className="branch-hero-shade" />
    <div className="branch-hero-content"><Link className="back-link" href="/"><ChevronLeft /> كل الفروع</Link><span className="hero-kicker"><i /> مجمع سعودي دنت</span><h1>{branch.name}</h1><p>{branch.description}</p>
      <div className="branch-location"><MapPin /> {branch.address}</div><div className="hero-actions"><a className="button" href="#departments">استكشف العيادات <ArrowLeft /></a><a className="button button-ghost" href="#gallery"><Images /> شاهد الصور</a></div>
    </div><div className="hero-corner-note"><span>{branch.city}</span><small>{branch.coordinates.lat.toFixed(4)}° N &nbsp; {branch.coordinates.lng.toFixed(4)}° E</small></div>
  </section>;
}

export function StickyBranchNav() { return <nav className="sticky-nav" aria-label="أقسام الفرع"><a href="#overview">نظرة عامة</a><a href="#departments">العيادات</a><a href="#doctors">الأطباء</a><a href="#gallery">الصور</a><a href="#services">الخدمات</a><a className="sticky-book" href="#contact"><CalendarDays /> احجز موعداً</a></nav>; }

export function StatsGrid({ branch }: { branch: Branch }) { return <div className="stats-grid">{branch.stats.map((stat, i) => <Reveal key={stat.label} delay={i * .08} className="stat-card"><strong>{stat.value}</strong><span>{stat.label}</span></Reveal>)}<Reveal delay={.24} className="stat-card stat-highlight"><Clock3 /><div><strong>حتى 11</strong><span>مساءً يومياً</span></div></Reveal></div>; }

export function DepartmentsGrid({ branch }: { branch: Branch }) { return <div className="department-grid">{branch.departments.map((department, i) => { const Icon = icons[department.icon] || Stethoscope; return <Reveal delay={i * .05} key={department.slug}><Link className="department-card" href={`/branch/${branch.slug}/department/${department.slug}`}><span className="department-icon"><Icon size={25} /></span><small>0{i + 1}</small><h3>{department.name}</h3><p>{department.description}</p><b>معرفة المزيد <ArrowLeft /></b></Link></Reveal>; })}</div>; }

export function DoctorsSection({ branch }: { branch: Branch }) { return <section className="section doctors-section" id="doctors"><div className="container"><SectionTitle eyebrow="فريق طبي متخصص" title="خبرات تعمل من أجل ابتسامتك" text="نماذج تعريفية لفريق الفرع؛ تُحدّث بيانات الأطباء وفق الجدول التشغيلي." />
    <div className="doctor-grid">{branch.doctors.map((doctor, i) => <Reveal key={doctor.name} delay={i * .08} className="doctor-card"><div className="doctor-avatar"><SafeImage src={doctor.image} alt={doctor.name} fill sizes="(max-width: 700px) 100vw, 33vw" fallbackLabel={doctor.name} /></div><div className="doctor-info"><small>{doctor.specialty}</small><h3>{doctor.name}</h3><p>{doctor.bio}</p><div><b>{doctor.experience} سنوات خبرة</b><button aria-label={`تفاصيل ${doctor.name}`}><ArrowLeft /></button></div></div></Reveal>)}</div></div></section>; }

export function GallerySection({ branch }: { branch: Branch }) { return <section className="section gallery-section" id="gallery"><div className="container"><SectionTitle eyebrow="من داخل الفرع" title="مساحات صُممت لراحتك" text="صور حقيقية توثق تفاصيل التجربة في سعودي دنت." light />
    <div className="gallery-grid">{branch.gallery.map((image, i) => <Reveal key={image.src} className={`gallery-item gallery-item-${(i % 5) + 1}`}><SafeImage src={image.src} alt={image.alt} fill sizes="(max-width: 700px) 100vw, 50vw" /><span>{image.alt}<small>{String(i + 1).padStart(2, "0")}</small></span></Reveal>)}</div></div></section>; }

export function ServicesGrid() { return <section className="section" id="services"><div className="container"><SectionTitle eyebrow="رحلة عناية متكاملة" title="كل ما تحتاجه في مكان واحد" /><div className="services-grid">{services.map(([name, text], i) => <Reveal key={name} delay={i * .04} className="service-card"><span>{String(i + 1).padStart(2, "0")}</span><div><h3>{name}</h3><p>{text}</p></div></Reveal>)}</div></div></section>; }

export function CTASection({ branchName }: { branchName: string }) { return <section className="cta"><div><small>خطوتك الأولى نحو ابتسامة أكثر ثقة</small><h2>نستقبلك في {branchName}</h2><p>احجز موعدك، وسيتواصل معك فريقنا لتنسيق الزيارة المناسبة.</p></div><a className="button button-light" href="tel:920003340"><CalendarDays /> احجز موعدك الآن</a></section>; }

export function DepartmentDetail({ branch, department }: { branch: Branch; department: Department }) { const Icon = icons[department.icon] || Stethoscope; const departmentImage = branch.gallery.find(x => x.category === (department.slug === "pediatric" ? "kids" : "treatment"))?.src; const relatedDoctor = branch.doctors[department.slug === "pediatric" ? 2 : department.slug === "orthodontics" ? 1 : 0] || branch.doctors[0]; return <main><section className="department-hero"><SafeImage src={departmentImage || branch.heroImage} fallbackSrc={departmentImage ? undefined : branch.heroFallback} alt={department.name} fill priority sizes="100vw" /><div className="branch-hero-shade" /><div className="department-hero-content"><Link href={`/branch/${branch.slug}`}><ChevronLeft /> العودة إلى {branch.name}</Link><span className="department-icon"><Icon size={28} /></span><h1>{department.name}</h1><p>{department.description}</p></div></section><section className="section"><div className="container detail-layout"><article><span className="eyebrow">رعاية مبنية حول احتياجك</span><h2>خطة واضحة، ونتيجة نستهدفها معاً</h2><p>تبدأ رحلتك بتقييم شامل وشرح الخيارات المتاحة، ثم تصميم خطة علاج تناسب حالتك وأولوياتك. نحرص في كل خطوة على الوضوح والراحة والمتابعة.</p><div className="service-points">{department.services.map((item) => <div key={item}><ShieldCheck /><span><b>{item}</b><small>بروتوكول عناية متكامل</small></span></div>)}</div></article><aside><h3>طبيب مرتبط بالتخصص</h3><div className="related-doctor"><b>{relatedDoctor.name}</b><small>{relatedDoctor.specialty}</small><span>{relatedDoctor.experience} سنوات خبرة</span></div><p>احجز موعد تقييم أولي مع فريق {department.name} في {branch.name}.</p><a className="button" href="tel:920003340">احجز استشارتك <ArrowLeft /></a></aside></div></section><section className="detail-gallery"><div className="container"><SectionTitle eyebrow="جولة سريعة" title={`من داخل ${branch.name}`} light /><div>{branch.gallery.slice(0,3).map(image => <figure key={image.src}><SafeImage src={image.src} alt={image.alt} fill sizes="33vw" /><figcaption>{image.alt}</figcaption></figure>)}</div><Link className="button button-light" href={`/branch/${branch.slug}#gallery`}>مشاهدة معرض الفرع <Images /></Link></div></section><CTASection branchName={branch.name} /></main>; }
